package cloud.CloudModule;

/**
* CloudModule/CloudHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cloud.idl
* dimanche 30 novembre 2025 17 h 08 WAT
*/

public final class CloudHolder implements org.omg.CORBA.portable.Streamable
{
  public cloud.CloudModule.Cloud value = null;

  public CloudHolder ()
  {
  }

  public CloudHolder (cloud.CloudModule.Cloud initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cloud.CloudModule.CloudHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
      cloud.CloudModule.CloudHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cloud.CloudModule.CloudHelper.type ();
  }

}
