package cloud.CloudModule;


/**
* CloudModule/CloudPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cloud.idl
* dimanche 30 novembre 2025 17 h 08 WAT
*/

public abstract class CloudPOA extends org.omg.PortableServer.Servant
 implements cloud.CloudModule.CloudOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("upload", new java.lang.Integer (0));
    _methods.put ("download", new java.lang.Integer (1));
    _methods.put ("deleteFile", new java.lang.Integer (2));
    _methods.put ("listFiles", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // CloudModule/Cloud/upload
       {
         String filename = in.read_string ();
         byte data[] = cloud.CloudModule.OctetSeqHelper.read (in);
         this.upload (filename, data);
         out = $rh.createReply();
         break;
       }

       case 1:  // CloudModule/Cloud/download
       {
         String filename = in.read_string ();
         byte $result[] = null;
         $result = this.download (filename);
         out = $rh.createReply();
           cloud.CloudModule.OctetSeqHelper.write (out, $result);
         break;
       }

       case 2:  // CloudModule/Cloud/deleteFile
       {
         String filename = in.read_string ();
         this.deleteFile (filename);
         out = $rh.createReply();
         break;
       }

       case 3:  // CloudModule/Cloud/listFiles
       {
         String $result[] = null;
         $result = this.listFiles ();
         out = $rh.createReply();
           cloud.CloudModule.StringSeqHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CloudModule/Cloud:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Cloud _this() 
  {
    return CloudHelper.narrow(
    super._this_object());
  }

  public Cloud _this(org.omg.CORBA.ORB orb) 
  {
    return CloudHelper.narrow(
    super._this_object(orb));
  }


} // class CloudPOA
