package cloud.CloudModule;


import org.omg.CORBA.Any;

/**
* CloudModule/CloudHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cloud.idl
* dimanche 30 novembre 2025 17 h 08 WAT
*/

abstract public class CloudHelper
{
  private static String  _id = "IDL:CloudModule/Cloud:1.0";

  public static void insert (Any a, Cloud that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static cloud.CloudModule.Cloud extract (Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (cloud.CloudModule.CloudHelper.id (), "Cloud");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static cloud.CloudModule.Cloud read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (CloudModule._CloudStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, cloud.CloudModule.Cloud value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static cloud.CloudModule.Cloud narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof cloud.CloudModule.Cloud)
      return (cloud.CloudModule.Cloud)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CloudModule._CloudStub stub = new CloudModule._CloudStub ();
      stub._set_delegate(delegate);
      return (Cloud) stub;
    }
  }

  public static cloud.CloudModule.Cloud unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof cloud.CloudModule.Cloud)
      return (cloud.CloudModule.Cloud)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      CloudModule._CloudStub stub = new CloudModule._CloudStub ();
      stub._set_delegate(delegate);
      return (Cloud) stub;
    }
  }

}
