package cloud.CloudModule;


/**
* CloudModule/CloudOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cloud.idl
* dimanche 30 novembre 2025 17 h 08 WAT
*/

public interface CloudOperations 
{
  void upload (String filename, byte[] data);
  byte[] download (String filename);
  void deleteFile (String filename);
  String[] listFiles ();
} // interface CloudOperations
