package cloud.CloudModule;


/**
* CloudModule/Cloud.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cloud.idl
* dimanche 30 novembre 2025 17 h 08 WAT
*/

public interface Cloud extends cloud.CloudModule.CloudOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface Cloud
