package cloud.CloudModule;


/**
* CloudModule/OctetSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cloud.idl
* dimanche 30 novembre 2025 17 h 08 WAT
*/


// Définir les types séquence
public final class OctetSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public byte value[] = null;

  public OctetSeqHolder ()
  {
  }

  public OctetSeqHolder (byte[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cloud.CloudModule.OctetSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
      cloud.CloudModule.OctetSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cloud.CloudModule.OctetSeqHelper.type ();
  }

}
