package cloud.CloudModule;


/**
* CloudModule/StringSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cloud.idl
* dimanche 30 novembre 2025 17 h 08 WAT
*/

public final class StringSeqHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public StringSeqHolder ()
  {
  }

  public StringSeqHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = cloud.CloudModule.StringSeqHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
      cloud.CloudModule.StringSeqHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return cloud.CloudModule.StringSeqHelper.type ();
  }

}
